### PR TITLE
use soft link vs stow for local vruby dirs

### PR DESCRIPTION
**Pull request by joshgoebel**

### CODE REVIEW

**Comment by joshgoebel** [comment]
Related: #17

**Comment by joefiorini** [comment]
So I'm not sure what's going on here, but the first example fails when I run it on my Mac. Reproduction steps:
1. `cd example`
2. Run `./0_start_here.sh`
3. Follow instructions to setup environment (`../bin/vruby vruby --from ../share`)

I got an error on the last step while it was trying to install bundler. Here is the output from the error:

```
Fetching: bundler-1.9.4.gem (100%)
Successfully installed bundler-1.9.4
dyld: lazy symbol binding failed: Symbol not found: _rb_str_new_static
  Referenced from: /src/vruby/example/.gem/ruby/2.2.1/gems/json-1.8.2/lib/json/ext/parser.bundle
  Expected in: flat namespace

dyld: Symbol not found: _rb_str_new_static
  Referenced from: /src/vruby/example/.gem/ruby/2.2.1/gems/json-1.8.2/lib/json/ext/parser.bundle
  Expected in: flat namespace

../bin/vruby: line 43:  5403 Trace/BPT trap: 5       gem install --no-user-install bundler
```

**Comment by joshgoebel** [comment]
Weird.  And does it work without --from ?

**Comment by joefiorini** [comment]
@yyyc514 `0_start_here.sh` runs `../bin/vruby install --to $install_to` and installs to `../share`. It does work without the `--from` which makes me wonder if the binary package was changed recently...

**Comment by joshgoebel** [comment]
>  It does work without the --from which makes me wonder if the binary package was changed recently...

Absolute vs relative paths matter with `ln`... if you pass --from the absolute path I bet it starts working?

**Comment by joshgoebel** [comment]
Getting from relative to absolute path with bash alone is pretty frustrating though... (for what is a one-liner in a higher level language)  Grrrr.

**Comment by joefiorini** [comment]
Wow, that did it. Can resolve that in the script?

**Comment by joefiorini** [comment]
If you can make it resolve the path I'd be happy to merge. I'd like to be able to use relative paths here if possible.

OTOH getting rid of the stow dependency would be pretty awesome, so if it's too much work we may be able to live with only absolute path support.

**Comment by joshgoebel** [comment]
I'll give it some thought.... it's just all the ways to do in just Bash it are pretty janky.

Outside of the examples I think the use case for someone passing a relative paths here is pretty small, no?

**Comment by joshgoebel** [comment]
Give that a shot.

**Comment by joefiorini** [comment]
It's been awhile, but I'm doing a little Ruby lately, so seeing if I can make a bit more progress on this. It's working great on this branch, so I'm pulling this in. Thanks and sorry for the huge delay!

**Pull request merged**
